### ISSUE TITLE
Some users end up with a null StatusMessageFilters object

### ISSUE THREAD

**Issue by robhruska** [robhruska/CalendarToSlack#10]
I'm not sure how, I went through all the code paths and didn't see a place where we could set it to null. Nothing stood out as significant about the user's Slack details.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at CalendarToSlack.Updater.MatchFilter(String subject, Dictionary`2 filters) in c:\Users\rob\Projects\CalendarToSlack\CalendarToSlack\Updater.cs:line 268
   at CalendarToSlack.Updater.GetUserMessage(CalendarEvent ev, RegisteredUser user) in c:\Users\rob\Projects\CalendarToSlack\CalendarToSlack\Updater.cs:line 239
   at CalendarToSlack.Updater.CheckUserStatusAndUpdate(RegisteredUser user, List`1 events) in c:\Users\rob\Projects\CalendarToSlack\CalendarToSlack\Updater.cs:line 147
   at CalendarToSlack.Updater.MarkBack(String userid) in c:\Users\rob\Projects\CalendarToSlack\CalendarToSlack\Updater.cs:line 140
   at CalendarToSlack.SlackCommandConsumer.HandleMessage(Dictionary`2 fields) in c:\Users\rob\Projects\CalendarToSlack\CalendarToSlack\SlackCommandConsumer.cs:line 164
   at CalendarToSlack.SlackCommandConsumer.Consume() in c:\Users\rob\Projects\CalendarToSlack\CalendarToSlack\SlackCommandConsumer.cs:line 113
```

**Comment by JDegner0129** [comment]
Custom statuses refactored this logic enough that it _may_ not be a problem anymore. Might be worth closing until we see it again.
